name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-tidy:
    name: Verify Linting
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Set up golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/v1.64.8/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.64.8

      - name: Run lint check
        run: make lint

      - name: Run tidy check
        run: |
          go mod tidy
          # Fail if go.mod or go.sum changed
          git diff --exit-code go.mod go.sum

      - name: Verify cross-compilation
        run: make build-cross

  test:
    name: Verify Unit Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        go:
        - '1.24'
    steps:
      - uses: actions/checkout@v5

      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}

      - name: Run unit tests
        run: make test-all

